### PR TITLE
Update Web App Manifest

### PR DESCRIPTION
**Pull request by hyjk2000**
This fixes the error in the [web app manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest).

### CODE REVIEW

**Comment by hyjk2000** [comment]
@hiveer This tells us the user is launching the app from home screen.

**Comment by just4fun** [comment]
@hiveer - Hey how are you! Long time no see!

**Comment by hiveer** [comment]
LOL(撸啊撸）

**Comment by just4fun** [comment]
I'm busy in meetings today so I didn't get any chance for this PR. I will have a look tomorrow. I promise.

**Comment by just4fun** [comment]
@hiveer FYI.

https://developers.google.com/web/fundamentals/web-app-manifest/#set_a_start_url

**Comment by just4fun** [comment]
tenor-206941318

**Comment by hiveer** [comment]
@just4fun  Thanks

**Pull request merged**
