### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by hyjk2000**
🆙

### CODE REVIEW

**Comment by just4fun** [comment]
I'd like to test the whole application in this weekend to make sure the new packages won't broke any functionalities.

**Comment by hyjk2000** [comment]
@just4fun I've tested it but it's always good to have more sets of eyes. The biggest changes would be React 16 here. As a result, I had to migrate to Enzyme 3. From Enzyme 3 there will be an adapter mechanic to decouple React version and Enzyme version. There are some breaking changes as well that you may want to check out.

**Comment by hyjk2000** [comment]
React 16 depends on `requestAnimationFrame` which may not be supported in test environment. Enzyme 3 explicitly depends on [raf](https://www.npmjs.com/package/raf) - a polyfill of `requestAnimationFrame`. I guess it's a good idea to include that polyfill in test setup.

**Comment by just4fun** [comment]
tenor-2595410

**Pull request merged**
