### PR TITLE
Add component for github-corner

### PR DESCRIPTION
**Pull request by just4fun**
Add component for http://tholman.com/github-corners/, then we can get more publicity for the repos.

Run it in your local to see whether you like it or not.

### CODE REVIEW

**Comment by hyjk2000** [comment]
I'm expecting a lower profile and less intrusive form on the bottom with a copyright announcement. https://buttons.github.io/

**Comment by just4fun** [comment]
@hyjk2000 I'm ok, we can close this MR once we create new one you mentioned.

**Comment by just4fun** [comment]
@hyjk2000 seems like the color for octocat has been changed (it was white before), and I found you did not update the default `Bram Naus` at the bottom.

More over, I like component, and I don't like adding something specific in simple html page, or we can also add google analytics into html directly as well.

How about you think?

**Comment by hyjk2000** [comment]
Why I prefer not to wrap the GitHub corner in a component? Because the two primary purposes of componentize don't apply in this case:

1. It's not part of the app: it doesn't update as the app state changes.
2. It's not to be reused.

The reason I changed the color scheme is to lower the contrast of the icon, making it less conspicuous, as it should be. We don't want it to be distractive.

As for the unsplash photo credit, that is how it meant to be, and it should only be presented at the landing page, where the photo is. I don't get what you mean by 'the default `Bram Naus`', that's the photographer's name.

**Comment by just4fun** [comment]
@hyjk2000 - Got your point and it makes sense to me.

Just update octocat to white color because I'd like it to be conspicuous. 🤓

**Pull request merged**
